@extends('backend.layouts.app')
@section('title','Consultation Service Details')
@section('content')
<div class="admin-panel ems-page">
  <div class="d-flex justify-content-between align-items-center mb-4"><div><p class="ems-kicker mb-1">Admin Portal</p><h2 class="admin-title mb-0">{{ $service->name }}</h2></div><a href="{{ route('admin.consultant-services.index') }}" class="btn btn-outline-secondary">Back</a></div>
  <div class="chart-card p-4">
    <div class="d-flex gap-2 mb-3"><span class="badge bg-{{ $service->status === 'approved' ? 'success' : ($service->status === 'rejected' ? 'danger' : 'warning') }}">{{ ucfirst($service->status ?? 'pending') }}</span></div>
    <dl class="row"><dt class="col-sm-3">Consultant</dt><dd class="col-sm-9">{{ $service->consultant?->display_name ?: $service->consultant?->company_name ?: '-' }}</dd><dt class="col-sm-3">Category</dt><dd class="col-sm-9">{{ $service->categoryModel?->name ?? $service->category ?? '-' }} / {{ $service->subcategoryModel?->name ?? '-' }}</dd><dt class="col-sm-3">Consultation Type</dt><dd class="col-sm-9">{{ ucfirst($service->consultation_type ?: ($service->is_online ? 'online' : 'offline')) }}</dd><dt class="col-sm-3">Business Type</dt><dd class="col-sm-9">{{ $service->business_type ?: '-' }}</dd><dt class="col-sm-3">Consultation Charges</dt><dd class="col-sm-9">{{ $service->formattedConsultationCharges() }}</dd><dt class="col-sm-3">Charges Detail</dt><dd class="col-sm-9" style="white-space:pre-line;">{{ $service->charges_detail ?: '-' }}</dd><dt class="col-sm-3">Time for Consultation</dt><dd class="col-sm-9">{{ $service->duration ?: '-' }}</dd><dt class="col-sm-3">Consultant Location</dt><dd class="col-sm-9">{{ $service->location ?: '-' }}<div class="small text-muted">Lat: {{ $service->latitude ?: '-' }}, Long: {{ $service->longitude ?: '-' }}</div></dd><dt class="col-sm-3">Geographical Service Area</dt><dd class="col-sm-9" style="white-space:pre-line;">{{ $service->service_area ?: '-' }}</dd><dt class="col-sm-3">Short Description</dt><dd class="col-sm-9">{{ $service->short_description ?: '-' }}</dd><dt class="col-sm-3">Detailed Description</dt><dd class="col-sm-9" style="white-space:pre-line;">{{ $service->description ?: '-' }}</dd></dl>
    @if($service->image_path)<div class="row g-3 mt-2"><div class="col-6 col-md-3"><img src="{{ asset($service->image_path) }}" alt="{{ $service->name }}" class="img-fluid rounded"></div></div>@endif
  </div>
</div>
@endsection
